### ISSUE TITLE
Type declaration file could not be found

### ISSUE THREAD

**Issue by CodeGetters** [intlify/vue-i18n-next#1491]
### Reporting a bug?

There are types at '.../node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings

### Expected behavior

```ts
import { createI18n } from "vue-i18n";

import type {
  I18n,
  I18nOptions,
  Locale,
  VueI18n,
  Composer,
  I18nMode,
} from "vue-i18n";
```

When I use the above code, my ts says I can't find the module declaration file.

It's fine when I modify an export in a dependent file: /node_modules/vue-i18n/package
```json
  "exports": {
    ".": {
      "import": {
        "node": "./index.mjs",
        "default": "./dist/vue-i18n.esm-bundler.js"
        // Here's what I added
       "types":"./dist/vue-i18n.d.ts"
      },
      "require": "./index.js"
    },
    "./dist/*": "./dist/*",
    "./index.mjs": "./index.mjs",
    "./package.json": "./package.json"
  },
```

### Reproduction

https://github.com/CodeGetters/studtwork_desk/tree/ae78b7538048c538dd2fe05153cba8d340db323a

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 4.04 GB / 15.65 GB
  Binaries:
    Node: 18.16.0 - D:\nvm_software\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nvm_software\nvm\nvm\node_global\yarn.CMD
    npm: 9.5.1 - D:\nvm_software\nodejs\npm.CMD
    pnpm: 8.6.11 - D:\nvm_software\nvm\nvm\node_global\pnpm.CMD 
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)  
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^7.0.0 => 7.0.0
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3
    vite: ^4.4.5 => 4.4.8
    vite-plugin-checker: ^0.6.1 => 0.6.1
    vite-plugin-compression: ^0.5.1 => 0.5.1
    vite-plugin-vue-devtools: ^1.0.0-beta.6 => 1.0.0-beta.6
    vite-plugin-vue-markdown: ^0.23.7 => 0.23.7
    vite-svg-loader: ^4.0.0 => 4.0.0
    vitest: ^0.34.1 => 0.34.1
    vue: ^3.3.4 => 3.3.4
    vue-i18n: ^9.2.2 => 9.2.2
    vue-lazyload: ^3.0.0 => 3.0.0
    vue-router: ^4.2.4 => 4.2.4
    vue-tsc: ^1.8.5 => 1.8.8
```

### Screenshot

![image](https://github.com/intlify/vue-i18n-next/assets/109447998/848a028a-b829-46fa-a8f1-0ec6508b0618)
![image](https://github.com/intlify/vue-i18n-next/assets/109447998/1b028cc3-5fb6-4ce4-a131-7eba210c1a84)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by 0xDarker** [comment]
same issue with vue-i18n@9.2.2

**Comment by BG7ZAG** [comment]
upgrade "vue-i18n": "^9.3.0-beta.25"

**Comment by 0xDarker** [comment]
> upgrade "vue-i18n": "^9.3.0-beta.25"

I upgrade to "9.3.0-beta.25", then run  "pnpm dev" reports as this :

```
ai-qm:dev: ✘ [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]
ai-qm:dev: 
ai-qm:dev:     ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21:
ai-qm:dev:       1373 │         let result = await callback({
ai-qm:dev:            ╵                      ^
ai-qm:dev: 
ai-qm:dev:     at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
ai-qm:dev:     at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
ai-qm:dev:     at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
ai-qm:dev:     at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
ai-qm:dev:     at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
ai-qm:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ai-qm:dev:     at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
ai-qm:dev:     at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
ai-qm:dev:     at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
ai-qm:dev:     at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)
ai-qm:dev: 
ai-qm:dev:   This error came from the "onResolve" callback registered here:
ai-qm:dev: 
ai-qm:dev:     ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
ai-qm:dev:       1292 │       let promise = setup({
ai-qm:dev:            ╵                     ^
ai-qm:dev: 
ai-qm:dev:     at setup (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)
ai-qm:dev:     at handlePlugins (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)
ai-qm:dev:     at buildOrContextImpl (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)
ai-qm:dev:     at Object.buildOrContext (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)
ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68
ai-qm:dev:     at new Promise (<anonymous>)
ai-qm:dev:     at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)
ai-qm:dev:     at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)
ai-qm:dev:     at prepareEsbuildOptimizerRun (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)
ai-qm:dev: 
ai-qm:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
ai-qm:dev: 
ai-qm:dev:     ../../node_modules/.pnpm/vue-i18n@9.3.0-beta.25_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
ai-qm:dev:       8 │ var shared = require('@intlify/shared');
ai-qm:dev:         ╵                      ~~~~~~~~~~~~~~~~~
ai-qm:dev: 
ai-qm:dev: /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649
ai-qm:dev:   let error = new Error(`${text}${summary}`);
ai-qm:dev:               ^
ai-qm:dev: 
ai-qm:dev: Error: Build failed with 1 error:
ai-qm:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
ai-qm:dev:     at failureErrorWithLog (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
ai-qm:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
ai-qm:dev:   errors: [
ai-qm:dev:     {
ai-qm:dev:       detail: Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
ai-qm:dev:           at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
ai-qm:dev:           at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
ai-qm:dev:           at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
ai-qm:dev:           at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
ai-qm:dev:           at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
ai-qm:dev:           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ai-qm:dev:           at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
ai-qm:dev:           at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
ai-qm:dev:           at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
ai-qm:dev:           at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13),
ai-qm:dev:       id: '',
ai-qm:dev:       location: {
ai-qm:dev:         column: 21,
ai-qm:dev:         file: '../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js',
ai-qm:dev:         length: 0,
ai-qm:dev:         line: 1373,
ai-qm:dev:         lineText: '        let result = await callback({\n' +
ai-qm:dev:           '    at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)\n' +
ai-qm:dev:           '    at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)\n' +
ai-qm:dev:           '    at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)\n' +
ai-qm:dev:           '    at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)\n' +
ai-qm:dev:           '    at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)\n' +
ai-qm:dev:           '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
ai-qm:dev:           '    at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21\n' +
ai-qm:dev:           '    at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34\n' +
ai-qm:dev:           '    at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)\n' +
ai-qm:dev:           '    at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)',
ai-qm:dev:         namespace: 'file',
ai-qm:dev:         suggestion: ''
ai-qm:dev:       },
ai-qm:dev:       notes: [
ai-qm:dev:         {
ai-qm:dev:           location: {
ai-qm:dev:             column: 20,
ai-qm:dev:             file: '../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js',
ai-qm:dev:             length: 0,
ai-qm:dev:             line: 1292,
ai-qm:dev:             lineText: '      let promise = setup({\n' +
ai-qm:dev:               '    at setup (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)\n' +
ai-qm:dev:               '    at handlePlugins (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)\n' +
ai-qm:dev:               '    at buildOrContextImpl (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)\n' +
ai-qm:dev:               '    at Object.buildOrContext (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)\n' +
ai-qm:dev:               '    at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68\n' +
ai-qm:dev:               '    at new Promise (<anonymous>)\n' +
ai-qm:dev:               '    at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)\n' +
ai-qm:dev:               '    at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)\n' +
ai-qm:dev:               '    at prepareEsbuildOptimizerRun (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)',
ai-qm:dev:             namespace: 'file',
ai-qm:dev:             suggestion: ''
ai-qm:dev:           },
ai-qm:dev:           text: 'This error came from the "onResolve" callback registered here:'
ai-qm:dev:         },
ai-qm:dev:         {
ai-qm:dev:           location: {
ai-qm:dev:             column: 21,
ai-qm:dev:             file: '../../node_modules/.pnpm/vue-i18n@9.3.0-beta.25_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs',
ai-qm:dev:             length: 17,
ai-qm:dev:             line: 8,
ai-qm:dev:             lineText: "var shared = require('@intlify/shared');",
ai-qm:dev:             namespace: '',
ai-qm:dev:             suggestion: ''
ai-qm:dev:           },
ai-qm:dev:           text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
ai-qm:dev:         }
ai-qm:dev:       ],
ai-qm:dev:       pluginName: 'vite:dep-pre-bundle',
ai-qm:dev:       text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package'
ai-qm:dev:     }
ai-qm:dev:   ],
ai-qm:dev:   warnings: []
ai-qm:dev: }
ai-qm:dev: 
ai-qm:dev: Node.js v18.17.1
ai-qm:dev:  ELIFECYCLE  Command failed with exit code 1.
```

**Comment by BG7ZAG** [comment]
> @intlify/shared

@intlify/shared 这个包也升级到 `9.3.0-beta.25` 试试

**Comment by CodeGetters** [comment]
> same issue with vue-i18n@9.2.2

  I switched the version of vue-i18n to 9.2.2 and used the following ts configuration to successfully package and display
  ```ts
  {
    "extends": "@vue/tsconfig/tsconfig.dom.json",
    "compilerOptions": {
      "baseUrl": ".",
      "paths": {
        "@/*": ["./src/*"]
      },
      "noEmit": true
    },
    "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
    "exclude": ["node_modules"],
    "references": [{ "path": "./tsconfig.node.json" }]
  }
  ```

**Comment by kazupon** [comment]
This issue has been resolved in the latest version of v9.3.0-beta

**Comment by ivanparramartinez** [comment]
No this hasn't been solved. I updated vue-I18n and the error persist. Really don't know what to do. My site is not running because of this error

**Comment by CodeGetters** [comment]
> No this hasn't been solved. I updated vue-I18n and the error persist. Really don't know what to do. My site is not running because of this error

If you need it urgently, I suggest you don't use the latest version. Anyway, I have lowered the version and haven't updated it. There is no problem now.

**Comment by ivanparramartinez** [comment]
> > No this hasn't been solved. I updated vue-I18n and the error persist. Really don't know what to do. My site is not running because of this error
> 
> If you need it urgently, I suggest you don't use the latest version. Anyway, I have lowered the version and haven't updated it. There is no problem now.

This is an awkward error. Yesterday everything was working fine and this morning when running the site throwed that error. I tried to uninstall to reinstall, to updgrade and downgrade and that annoying error it's still there. Really feels like there is no exit.

**Comment by CodeGetters** [comment]
> > > No this hasn't been solved. I updated vue-I18n and the error persist. Really don't know what to do. My site is not running because of this error
> > 
> > If you need it urgently, I suggest you don't use the latest version. Anyway, I have lowered the version and haven't updated it. There is no problem now.
> 
> This is an awkward error. Yesterday everything was working fine and this morning when running the site throwed that error. I tried to uninstall to reinstall, to updgrade and downgrade and that annoying error it's still there. Really feels like there is no exit. 

I also have a deep understanding of such problems. Let me share my experience in problem solving.
First of all, you should first recall whether there has been a change in dependence from yesterday to today, which may be caused by other dependencies.
Secondly, By lowering the version, so far, I have no problem using 9.0.0.
Finally, it is suggested to restart the ide when modifying the dependency to avoid some reasons caused by the ide.
The above is my experience in solving this problem, which is also helpful to you.👀

**Comment by ivanparramartinez** [comment]
> 

There wasn't any change from night to morning in that part. I mean, it's a package which wasn't updated or something. The other thing right now is that I downgraded it to 9.1.8 and it runs well on localhost but in docker persist the error. What could be the error on docker?

**Comment by ivanparramartinez** [comment]
> 

There wasn't any change from night to morning in that part. I mean, it's a package which wasn't updated or something. The other thing right now is that I downgraded it to 9.1.8 and it runs well on localhost but in docker persist the error. What could be the error on docker?

**Comment by CodeGetters** [comment]
> > 
> 
> There wasn't any change from night to morning in that part. I mean, it's a package which wasn't updated or something. The other thing right now is that I downgraded it to 9.1.8 and it runs well on localhost but in docker persist the error. What could be the error on docker?

Is it normal for you to pack locally? If it is normal, there should be no mistakes in docker.

**Comment by YRYG** [comment]
> docker



> > 
> 
> There wasn't any change from night to morning in that part. I mean, it's a package which wasn't updated or something. The other thing right now is that I downgraded it to 9.1.8 and it runs well on localhost but in docker persist the error. What could be the error on docker?

Docker may have been updated to the latest version

**Comment by hhhawaii** [comment]
> > 升级“vue-i18n”：“^9.3.0-beta.25”
> 
> 我升级到“9.3.0-beta.25”，然后运行“pnpm dev”报告，如下所示：
> 
> ```
> ai-qm:dev: ✘ [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]
> ai-qm:dev: 
> ai-qm:dev:     ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21:
> ai-qm:dev:       1373 │         let result = await callback({
> ai-qm:dev:            ╵                      ^
> ai-qm:dev: 
> ai-qm:dev:     at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
> ai-qm:dev:     at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
> ai-qm:dev:     at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
> ai-qm:dev:     at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
> ai-qm:dev:     at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
> ai-qm:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ai-qm:dev:     at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
> ai-qm:dev:     at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
> ai-qm:dev:     at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
> ai-qm:dev:     at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)
> ai-qm:dev: 
> ai-qm:dev:   This error came from the "onResolve" callback registered here:
> ai-qm:dev: 
> ai-qm:dev:     ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
> ai-qm:dev:       1292 │       let promise = setup({
> ai-qm:dev:            ╵                     ^
> ai-qm:dev: 
> ai-qm:dev:     at setup (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)
> ai-qm:dev:     at handlePlugins (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)
> ai-qm:dev:     at buildOrContextImpl (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)
> ai-qm:dev:     at Object.buildOrContext (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)
> ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68
> ai-qm:dev:     at new Promise (<anonymous>)
> ai-qm:dev:     at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)
> ai-qm:dev:     at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)
> ai-qm:dev:     at prepareEsbuildOptimizerRun (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)
> ai-qm:dev: 
> ai-qm:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
> ai-qm:dev: 
> ai-qm:dev:     ../../node_modules/.pnpm/vue-i18n@9.3.0-beta.25_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
> ai-qm:dev:       8 │ var shared = require('@intlify/shared');
> ai-qm:dev:         ╵                      ~~~~~~~~~~~~~~~~~
> ai-qm:dev: 
> ai-qm:dev: /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649
> ai-qm:dev:   let error = new Error(`${text}${summary}`);
> ai-qm:dev:               ^
> ai-qm:dev: 
> ai-qm:dev: Error: Build failed with 1 error:
> ai-qm:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
> ai-qm:dev:     at failureErrorWithLog (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
> ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
> ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
> ai-qm:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
> ai-qm:dev:   errors: [
> ai-qm:dev:     {
> ai-qm:dev:       detail: Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
> ai-qm:dev:           at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
> ai-qm:dev:           at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
> ai-qm:dev:           at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
> ai-qm:dev:           at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
> ai-qm:dev:           at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
> ai-qm:dev:           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ai-qm:dev:           at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
> ai-qm:dev:           at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
> ai-qm:dev:           at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
> ai-qm:dev:           at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13),
> ai-qm:dev:       id: '',
> ai-qm:dev:       location: {
> ai-qm:dev:         column: 21,
> ai-qm:dev:         file: '../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js',
> ai-qm:dev:         length: 0,
> ai-qm:dev:         line: 1373,
> ai-qm:dev:         lineText: '        let result = await callback({\n' +
> ai-qm:dev:           '    at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)\n' +
> ai-qm:dev:           '    at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)\n' +
> ai-qm:dev:           '    at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)\n' +
> ai-qm:dev:           '    at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)\n' +
> ai-qm:dev:           '    at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)\n' +
> ai-qm:dev:           '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
> ai-qm:dev:           '    at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21\n' +
> ai-qm:dev:           '    at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34\n' +
> ai-qm:dev:           '    at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)\n' +
> ai-qm:dev:           '    at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)',
> ai-qm:dev:         namespace: 'file',
> ai-qm:dev:         suggestion: ''
> ai-qm:dev:       },
> ai-qm:dev:       notes: [
> ai-qm:dev:         {
> ai-qm:dev:           location: {
> ai-qm:dev:             column: 20,
> ai-qm:dev:             file: '../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js',
> ai-qm:dev:             length: 0,
> ai-qm:dev:             line: 1292,
> ai-qm:dev:             lineText: '      let promise = setup({\n' +
> ai-qm:dev:               '    at setup (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)\n' +
> ai-qm:dev:               '    at handlePlugins (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)\n' +
> ai-qm:dev:               '    at buildOrContextImpl (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)\n' +
> ai-qm:dev:               '    at Object.buildOrContext (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)\n' +
> ai-qm:dev:               '    at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68\n' +
> ai-qm:dev:               '    at new Promise (<anonymous>)\n' +
> ai-qm:dev:               '    at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)\n' +
> ai-qm:dev:               '    at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)\n' +
> ai-qm:dev:               '    at prepareEsbuildOptimizerRun (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)',
> ai-qm:dev:             namespace: 'file',
> ai-qm:dev:             suggestion: ''
> ai-qm:dev:           },
> ai-qm:dev:           text: 'This error came from the "onResolve" callback registered here:'
> ai-qm:dev:         },
> ai-qm:dev:         {
> ai-qm:dev:           location: {
> ai-qm:dev:             column: 21,
> ai-qm:dev:             file: '../../node_modules/.pnpm/vue-i18n@9.3.0-beta.25_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs',
> ai-qm:dev:             length: 17,
> ai-qm:dev:             line: 8,
> ai-qm:dev:             lineText: "var shared = require('@intlify/shared');",
> ai-qm:dev:             namespace: '',
> ai-qm:dev:             suggestion: ''
> ai-qm:dev:           },
> ai-qm:dev:           text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
> ai-qm:dev:         }
> ai-qm:dev:       ],
> ai-qm:dev:       pluginName: 'vite:dep-pre-bundle',
> ai-qm:dev:       text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package'
> ai-qm:dev:     }
> ai-qm:dev:   ],
> ai-qm:dev:   warnings: []
> ai-qm:dev: }
> ai-qm:dev: 
> ai-qm:dev: Node.js v18.17.1
> ai-qm:dev:  ELIFECYCLE  Command failed with exit code 1.
> ```

请问你解决了吗

**Comment by CodeGetters** [comment]
> > > 升级“vue-i18n”：“^9.3.0-beta.25”
> > 
> > 我升级到“9.3.0-beta.25”，然后运行“pnpm dev”报告，如下所示：
> > 
> > ```
> > ai-qm:dev: ✘ [ERROR] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle]
> > ai-qm:dev: 
> > ai-qm:dev:     ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21:
> > ai-qm:dev:       1373 │         let result = await callback({
> > ai-qm:dev:            ╵                      ^
> > ai-qm:dev: 
> > ai-qm:dev:     at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
> > ai-qm:dev:     at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
> > ai-qm:dev:     at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
> > ai-qm:dev:     at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
> > ai-qm:dev:     at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
> > ai-qm:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > ai-qm:dev:     at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
> > ai-qm:dev:     at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
> > ai-qm:dev:     at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
> > ai-qm:dev:     at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)
> > ai-qm:dev: 
> > ai-qm:dev:   This error came from the "onResolve" callback registered here:
> > ai-qm:dev: 
> > ai-qm:dev:     ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
> > ai-qm:dev:       1292 │       let promise = setup({
> > ai-qm:dev:            ╵                     ^
> > ai-qm:dev: 
> > ai-qm:dev:     at setup (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)
> > ai-qm:dev:     at handlePlugins (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)
> > ai-qm:dev:     at buildOrContextImpl (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)
> > ai-qm:dev:     at Object.buildOrContext (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)
> > ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68
> > ai-qm:dev:     at new Promise (<anonymous>)
> > ai-qm:dev:     at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)
> > ai-qm:dev:     at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)
> > ai-qm:dev:     at prepareEsbuildOptimizerRun (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)
> > ai-qm:dev: 
> > ai-qm:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
> > ai-qm:dev: 
> > ai-qm:dev:     ../../node_modules/.pnpm/vue-i18n@9.3.0-beta.25_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs:8:21:
> > ai-qm:dev:       8 │ var shared = require('@intlify/shared');
> > ai-qm:dev:         ╵                      ~~~~~~~~~~~~~~~~~
> > ai-qm:dev: 
> > ai-qm:dev: /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649
> > ai-qm:dev:   let error = new Error(`${text}${summary}`);
> > ai-qm:dev:               ^
> > ai-qm:dev: 
> > ai-qm:dev: Error: Build failed with 1 error:
> > ai-qm:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
> > ai-qm:dev:     at failureErrorWithLog (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
> > ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
> > ai-qm:dev:     at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
> > ai-qm:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
> > ai-qm:dev:   errors: [
> > ai-qm:dev:     {
> > ai-qm:dev:       detail: Error: Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package
> > ai-qm:dev:           at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
> > ai-qm:dev:           at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)
> > ai-qm:dev:           at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
> > ai-qm:dev:           at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
> > ai-qm:dev:           at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
> > ai-qm:dev:           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > ai-qm:dev:           at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
> > ai-qm:dev:           at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34
> > ai-qm:dev:           at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
> > ai-qm:dev:           at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13),
> > ai-qm:dev:       id: '',
> > ai-qm:dev:       location: {
> > ai-qm:dev:         column: 21,
> > ai-qm:dev:         file: '../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js',
> > ai-qm:dev:         length: 0,
> > ai-qm:dev:         line: 1373,
> > ai-qm:dev:         lineText: '        let result = await callback({\n' +
> > ai-qm:dev:           '    at packageEntryFailure (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)\n' +
> > ai-qm:dev:           '    at resolvePackageEntry (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28686:9)\n' +
> > ai-qm:dev:           '    at tryNodeResolve (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)\n' +
> > ai-qm:dev:           '    at Context.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)\n' +
> > ai-qm:dev:           '    at Object.resolveId (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)\n' +
> > ai-qm:dev:           '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
> > ai-qm:dev:           '    at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21\n' +
> > ai-qm:dev:           '    at async file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39941:34\n' +
> > ai-qm:dev:           '    at async requestCallbacks.on-resolve (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)\n' +
> > ai-qm:dev:           '    at async handleRequest (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)',
> > ai-qm:dev:         namespace: 'file',
> > ai-qm:dev:         suggestion: ''
> > ai-qm:dev:       },
> > ai-qm:dev:       notes: [
> > ai-qm:dev:         {
> > ai-qm:dev:           location: {
> > ai-qm:dev:             column: 20,
> > ai-qm:dev:             file: '../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js',
> > ai-qm:dev:             length: 0,
> > ai-qm:dev:             line: 1292,
> > ai-qm:dev:             lineText: '      let promise = setup({\n' +
> > ai-qm:dev:               '    at setup (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:39921:19)\n' +
> > ai-qm:dev:               '    at handlePlugins (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)\n' +
> > ai-qm:dev:               '    at buildOrContextImpl (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)\n' +
> > ai-qm:dev:               '    at Object.buildOrContext (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)\n' +
> > ai-qm:dev:               '    at /Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68\n' +
> > ai-qm:dev:               '    at new Promise (<anonymous>)\n' +
> > ai-qm:dev:               '    at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)\n' +
> > ai-qm:dev:               '    at Object.context (/Users/xw/Projects/turbo/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)\n' +
> > ai-qm:dev:               '    at prepareEsbuildOptimizerRun (file:///Users/xw/Projects/turbo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.4_sass@1.65.1/node_modules/vite/dist/node/chunks/dep-df561101.js:45967:35)',
> > ai-qm:dev:             namespace: 'file',
> > ai-qm:dev:             suggestion: ''
> > ai-qm:dev:           },
> > ai-qm:dev:           text: 'This error came from the "onResolve" callback registered here:'
> > ai-qm:dev:         },
> > ai-qm:dev:         {
> > ai-qm:dev:           location: {
> > ai-qm:dev:             column: 21,
> > ai-qm:dev:             file: '../../node_modules/.pnpm/vue-i18n@9.3.0-beta.25_vue@3.3.4/node_modules/vue-i18n/dist/vue-i18n.cjs',
> > ai-qm:dev:             length: 17,
> > ai-qm:dev:             line: 8,
> > ai-qm:dev:             lineText: "var shared = require('@intlify/shared');",
> > ai-qm:dev:             namespace: '',
> > ai-qm:dev:             suggestion: ''
> > ai-qm:dev:           },
> > ai-qm:dev:           text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
> > ai-qm:dev:         }
> > ai-qm:dev:       ],
> > ai-qm:dev:       pluginName: 'vite:dep-pre-bundle',
> > ai-qm:dev:       text: 'Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package'
> > ai-qm:dev:     }
> > ai-qm:dev:   ],
> > ai-qm:dev:   warnings: []
> > ai-qm:dev: }
> > ai-qm:dev: 
> > ai-qm:dev: Node.js v18.17.1
> > ai-qm:dev:  ELIFECYCLE  Command failed with exit code 1.
> > ```
> 
> 请问你解决了吗

用9.0.0试试吧 我用的这个没问题

**Comment by YRYG** [comment]
> 我也出现这个报错Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@intlify/shared" package [plugin vite:dep-pre-bundle] 但是我的项目中没有找到@intlify/shared文件

改一下vue-i18n这个包的版本。@intlify/shared是vue-i18n的依赖包

**Comment by u10k** [comment]
Fix the problem with version 9.0.0
