### ISSUE TITLE
how to use the production build (*.prod.js) 

### ISSUE THREAD

**Issue by Alymbek** [intlify/vue-i18n-next#219]
### vue & vue-i18n version
- vue: ^3.0.4
- vue-i18n: ^9.0.0-beta.10

### What is Expected?
Need manual/guide to make/configure the production build.
Or disable that warning message in Console.

### What is actually happening?
showing message in Console:
```
You are running a development build of vue-i18n.
Make sure to use the production build (*.prod.js) when deploying for production.
```

![prod](https://user-images.githubusercontent.com/2016702/101454681-caefac00-394a-11eb-8cbc-9665577e311c.PNG)

**Comment by rafamanzo** [comment]
Fixed it configuring webpack:

```
        resolve: {
          alias: {
            "vue-i18n": "vue-i18n/dist/vue-i18n.esm-browser.prod.js"
          }
        }
```

Notice the you may need to chenge the `esm-browser` part according to your application.

**Comment by Alymbek** [comment]
hi, dear @rafamanzo.
thank you for your job!

yes, now it is working without any messages in console.

my webpack config:

```
resolve: {
		alias: {
			"vue-i18n": "vue-i18n/dist/vue-i18n.esm-browser.prod.js",
			vue$: "vue/dist/vue.runtime.esm-bundler.js",
		},
}
```

hi, dear @kazupon , any comment from your side?
is it right approach for this issue?

**Comment by kazupon** [comment]
I've just released out latest version.

- `vue-i18n`: 9.0.0-beta.15
- `@intlify/vue-i18n-loader`: 2.0.0-beta.3

you don't need to configure `resolve.alias`.

**Comment by Alymbek** [comment]
hi, dear @kazupon 
I just updated to latest version as you mentioed.

but still getting same messages in Console.

**Comment by kazupon** [comment]
In webpack case, you need to bundle with `production` mode.

**Comment by Alymbek** [comment]
wow, it is working now!
thank you, dear @kazupon.

**Comment by kuanyui** [comment]
Curious anyway to suppress this warning manually during developing? It's very confusing and mixed with the real warnings I need to read...

Still visible under development with following versions:
- vue: 3.0.7
- vue-i18n: 9.0.0

**Comment by kuanyui** [comment]
Can this warning message be hide manually during development? It's very confusing and easy to be mixed with the warning messages I really want to read.
