### ISSUE TITLE
Incorrect warnings around fallback

### ISSUE THREAD

**Issue by daniesg** [intlify/vue-i18n-next#373]
### vue & vue-i18n version
- vue: 3.0.5
- vue-i18n: 9.0.0

### What is Expected?
[The docs](https://vue-i18n.intlify.dev/guide/essentials/local.html) have an example of using both local and global translations in a component. It notes that:
> And also, as explained the here, note that, by default, falling back to global scope generates two warnings in the console:
```
[intlify] Not found 'message.greeting' key in 'ja' locale messages.
[intlify] Fall back to translate 'message.greeting' with root locale.
```

It also states that
> To suppress these warnings (while keeping those which warn of the total absence of translation for the given key) set silentTranslationWarn: true, and silentFallbackWarn: true when initializing the createI18n.

### What is actually happening?
Instead what I'm seeing is only one warning
```
[intlify] Not found 'message.greeting' key in 'ja' locale messages.
```

When I add only `silentFallbackWarn: true`, there is no difference. And if I add `silentTranslationWarn: true` (with and without `silentFallbackWarn`), it silences all missing translation warnings, even those where it couldn't find it in the global messages.

Are the docs out of date or is this a bug?

**Comment by kazupon** [comment]
Thank you for your reporting!
This is the bug.

I'll try to fix it!

**Comment by kazupon** [comment]
I've fixed at #374

**Comment by daniesg** [comment]
Thanks for the fast response!

**Comment by johannesstricker** [comment]
I think this is still an issue (or again, maybe) on version `9.1.6`. I'm using this setup:
```
export const i18nPlugin = createI18n({
  legacy: true,
  locale: 'en',
  fallbackLocale: 'en',
  messages,
  silentFallbackWarn: true,
});
```

Then, in a component I'm using local messages mixed with global messages:
```
export default {
  name: 'SomeComponent',
  i18n: {
    messages: {
      en: { hello: 'Hello World!' },
    },
  },
};
```

I'm getting these errors:
```
[intlify] Not found 'path.to.key' key in 'en' locale messages.
[intlify] Fall back to translate 'path.to.key' with root locale.
```

**Comment by kazupon** [comment]
Hmm 🤔, If you are possible, Could you give us the minimum reproduction codes, please? 🙏

**Comment by Coffcer** [comment]
i have the same issue.  v9.1.6

```
const i18n = createI18n({
  locale: 'en',
  messages,,
  silentFallbackWarn: true
})
app.use(i18n)


function setup () {
  const { t } = useI18n({
      messages,
      fallbackWarn: false
   })

  return {
    t
  }
 }

```

**Comment by themegaphoenix** [comment]
> just installed version `9.2.0-beta.12` with `yarn add vue-i18n@next`, and issue is fixed with `fallbackWarn: false`
> 
> but now I have `[intlify] Not supported 'preserve'.` warning

I suffer from the same issue

**Comment by kazupon** [comment]
API docs said on `fallbackWarn`:
https://vue-i18n.intlify.dev/api/composition.html#fallbackwarn

>Whether suppress fall back warnings when localization fails.

> but now I have `[intlify] Not supported 'preserve'.` warning

This warning is output when you use the deprecated feature in v9.x
ref:
https://vue-i18n.intlify.dev/guide/migration/breaking.html#remove-preservedirectivecontent-option
