### ISSUE TITLE
Warn You are running the esm-bundler build of vue-i18n.

### ISSUE THREAD

**Issue by supachailllpay** [intlify/vue-i18n-next#391]
**Module versions:**
 - Vue CLI: 4.5.11
 - `vue-cli-plugin-i18n`: 2.0.0

**To Reproduce**
1. Run `vue create project` (select `Default (Vue 3 Preview) ([Vue 3] babel, eslint)`)
2. Run `vue add i18n`
3. Run `npm run serve`

**Expected behavior**
This warning should be able to be removed by setting plugin options.

**Screenshots**
<img width="705" alt="Screen Shot 2564-03-11 at 03 02 47" src="https://user-images.githubusercontent.com/5978906/110690405-7a703f00-8216-11eb-8751-0f9fceb49907.png">

**Additional context**
It seems that the problem is the `__INTLIFY_PROD_DEVTOOLS__` flag is missing.

**Comment by kazupon** [comment]
@supachailllpay 
Thank you for your reporting!

Does this mean that the problem in this issue is also occurring in productiion?

**Comment by supachailllpay** [comment]
No, It only shows in development. You can see from my screenshot line 38 (sorry, I couldn't find the actual source code).

I think the problem is here: 

https://github.com/intlify/vue-cli-plugin-i18n/blob/266fe3055362dfa4350b4631a448694b53876a9a/index.js#L44-L48

There is no `__INTLIFY_PROD_DEVTOOLS__` flag so it always show the warning in development. Unless you add an additional webpack config to set this up. But it is inconvenient since other flags can be set through the plugin options.

Or maybe this flag should not be required to explicitly set?

Thank you.

**Comment by kazupon** [comment]
fixed!
you can check latest version!

**Comment by changweihua** [comment]
"vue-i18n": "^9.1.6",

![image](https://user-images.githubusercontent.com/2877201/115523747-f3f05800-a2bf-11eb-9afe-3448821ce5d7.png)

it will always be true ?

**Comment by gerbenvandekraats** [comment]
I just created a new Vue 3 project and i'm still getting this warning. What am i doing wrong?

**@vue/cli 4.5.12:**
```
"dependencies": {
	"vue": "^3.0.0",
	"vue-i18n": "^9.1.0",
},
	"devDependencies": {
	"@intlify/vue-i18n-loader": "^2.1.0",
}
```

**Comment by nicojmb** [comment]
I can confirm that the alert is still showing in DEV mode.

![image](https://user-images.githubusercontent.com/5610392/119050443-27f39180-b9c2-11eb-8f56-9debe31e9f86.png)

**Comment by Oleksii14** [comment]
@kazupon I am getting

```
Uncaught ReferenceError: __INTLIFY_PROD_DEVTOOLS__ is not defined
```

in production. Can you tell how to fix that?

**Comment by supachailllpay** [comment]
I can confirm this too (**vue-i18n@9.1.6**).

<img width="702" alt="Screen Shot 2564-05-21 at 20 13 24" src="https://user-images.githubusercontent.com/5978906/119142950-4369a580-ba71-11eb-93f3-4e41bd2f3ff7.png">

At line 42, It will always `true` for development mode.

It seems that statement `typeof true === 'boolean'` come from misc.ts:

https://github.com/intlify/vue-i18n-next/blob/7aacca70f3d9c60a0d9377948889ca0da03686f5/packages/vue-i18n/src/misc.ts#L39-L41

which build from rollup.config.js

https://github.com/intlify/vue-i18n-next/blob/7aacca70f3d9c60a0d9377948889ca0da03686f5/rollup.config.js#L238

So I'm not sure if this is intended behavior? If true, I think the message doesn't make sense anymore and there should be a way to turn it off.

@kazupon

**Comment by Topograph** [comment]
i got the following error in my production build only: "__ intlify_prod_devtools __ is not defined" preventing my whole app from executing.

added the following code to my webpack configuration: 
`new webpack.DefinePlugin({
        __INTLIFY_PROD_DEVTOOLS__ : 'false'
 })`

feels like a dirty workaround but helps me for now

**Comment by kazupon** [comment]
As I commented in the following URL, this is a bug.
https://github.com/intlify/vue-i18n-next/issues/529#issuecomment-860060254

If you would like to avoid this issue, you need to specify `__INTLIFY_PROD_DEVTOOLS__` flag on bundler configuration
About this flag, see the below URL:
https://vue-i18n.intlify.dev/guide/advanced/optimization.html#reduce-bundle-size-with-feature-build-flags

By the way, This fix will be officially released in v9.2.
Currently, the alpha version of v9.2 has been released.
This version is not yet stable, but it can be used in much the same way as v9.1, except for the support for TypeScript, which is unaffected by the disruptive changes.

**Comment by ztiromoritz** [comment]
I have the same situation as @supachailllpay described in its last message. 

The warning is shown, even if all four env variables (`__VUE_I18N_FULL_INSTALL__, __VUE_I18N_LEGACY_API__, __VUE_I18N_PROD_DEVTOOLS__, __INTLIFY_PROD_DEVTOOLS__`) are set. 

To avoid the message completly `process.env.NODE_ENV` has to be set  to 'production' as well. 

So the messege will be there in development, even if you configure all "feature flags" as the warning suggests.

**Comment by Psycarlo** [comment]
I am using version `9.2.0-beta.22` and still get this message

**Comment by wladston** [comment]
I am using version `9.2.0-beta.23` and I still get this message…

**Comment by 0xsha256** [comment]
> "vue-i18n": "^9.1.6",
> 
> ![image](https://user-images.githubusercontent.com/2877201/115523747-f3f05800-a2bf-11eb-9afe-3448821ce5d7.png)
> 
> it will always be true ?

Haha, yes!

**Comment by daveharig** [comment]
+1

**Comment by littlecxm** [comment]
+1

**Comment by sicbb** [comment]
+1

**Comment by MNormatov** [comment]
+1

**Comment by philippedasilva-orizone** [comment]
+1

**Comment by juliandreas** [comment]
+1

**Comment by zeroinformatique** [comment]
+1

**Comment by dajpes** [comment]
Hey @[kazupon](https://github.com/kazupon) any update on this?

**Comment by M1CK431** [comment]
Hi!

Same issue here with vite bundler.

Finally I add this in my `index.html`, just before `<script type="module" src="/src/main.js"></script>`:
```html
    <script>
      // Workaround stupid i18n console warning
      Object.assign(window, {
        __VUE_I18N_FULL_INSTALL__: true,
        __INTLIFY_PROD_DEVTOOLS__: false,
        __VUE_I18N_LEGACY_API__: true
      });
    </script>
```

And no more console warning :wink:

**Comment by vallemar** [comment]
I have this problem in version "vue-i18n": "^9.2.2", my configuration:
```json
  "dependencies": {
    "@vueuse/core": "^9.3.0",
    "pinia": "^2.0.22",
    "vue": "^3.2.39",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.1.5"
  },
  "devDependencies": {
    "@types/node": "^18.7.17",
    "@vitejs/plugin-vue": "^3.1.0",
    "autoprefixer": "^10.4.12",
    "postcss": "^8.4.16",
    "sass": "^1.55.0",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.5.4",
    "vite": "^3.1.4",
    "vue-tsc": "^0.29.8"
  }
```

**Comment by devmount** [comment]
+1

**Comment by Flo2315** [comment]
+1

**Comment by kr580vm80a** [comment]
+1

**Comment by dralos** [comment]
i have the same problem, my configuration:
`
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.3.0",
    "@fortawesome/free-solid-svg-icons": "^6.3.0",
    "@fortawesome/vue-fontawesome": "^3.0.3",
    "@popperjs/core": "^2.11.6",
    "axios": "^1.3.4",
    "bootstrap": "^5.2.3",
    "jquery": "^3.6.3",
    "vee-validate": "^4.7.4",
    "vue": "^3.2.45",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.1.6",
    "vuetify": "^3.1.7",
    "vuex": "^4.1.0",
    "yup": "^1.0.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "vite": "^4.1.0"
  } 
`

**Comment by rezelute** [comment]
Any updates on removing this error from the console yet?

**Comment by mw-shub** [comment]
any update? still exist in "vue-i18n": "^9.2.2"

**Comment by M1CK431** [comment]
@rezelute @mw-shub have you try [my workarnoud](https://github.com/intlify/vue-i18n-next/issues/391#issuecomment-1237253910)?

**Comment by devmount** [comment]
@M1CK431 I'm sure your workaround works, but I don't like to pollute my index.html with suppressing false warnings. But thanks anyway.

@kazupon Unfortunately this issue isn't solved (as you told in https://github.com/intlify/vue-i18n-next/issues/391#issuecomment-860700309. Is there a chance to look into this again?

**Comment by rezelute** [comment]
@M1CK431 i did and it worked as temporary workaround so thank you for this. However, this is one of those which might get fixed in the future in an update and we would have added to index and forget to remove it later. I agree with devmount that it also pollutes index.
