### ISSUE TITLE
<i18n-t> doesn't work when nested inside <transition>

### ISSUE THREAD

**Issue by semiaddict** [intlify/vue-i18n-next#722]
### Reporting a bug?

I am trying to use [Component Interpolation](https://vue-i18n.intlify.dev/guide/advanced/component.html#component-interpolation) with the `<i18n-t>` component which is nested inside a [`<transition>`](https://v3.vuejs.org/api/built-in-components.html#transition) component, but this causes the error `TypeError: composer is null` from the method `getComposer`.

The code works perfectly if I remove the `<transition>` component.

### Expected behavior

The `<i18n-t>` component outputs the translated string.

### Reproduction

Here's a repo that can reproduce the problem: https://github.com/semiaddict/vue-i18n-transition-bug

The repo contains only a simple App component with the following code:

```vue
<template>
  <transition name="fade">
      <i18n-t keypath="hello" tag="p">
        <template #world>
            <b>{{ $t("world") }}</b>
        </template>
      </i18n-t>
  </transition>
</template>

<script>
export default {
  i18n: {
    messages: {
      en: {
        hello: "Hello {world}",
        world: "world!",
      },
    },
  }
};
</script>
```

### System Info

```shell
System:
  OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
  CPU: (8) x64 Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz
  Memory: 1.90 GB / 7.77 GB
  Container: Yes
  Shell: 4.4.12 - /bin/bash
Binaries:
  Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
  Yarn: 1.22.15 - ~/.nvm/versions/node/v14.16.0/bin/yarn
  npm: 7.24.1 - ~/.nvm/versions/node/v14.16.0/bin/npm
npmPackages:
  vue: ^3.2.6 => 3.2.19 
  vue-i18n: ^9.1.8 => 9.1.8
```

### Screenshot

Here's a screenshot of the console with the error message:

![image](https://user-images.githubusercontent.com/522064/136169187-336f5acf-bc31-4787-b8da-2c3ef75cff2b.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by Saibamen** [comment]
Related: https://github.com/louislam/uptime-kuma/pull/451#issuecomment-936011167 ?

**Comment by kazupon** [comment]
I've just released v9.1.9
Please check it!

**Comment by semiaddict** [comment]
Thank you @kazupon for your reactivity!
The error is gone.
I am, however, still experiencing an issue, similar to #708. which I will post there.
