### ISSUE TITLE
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.

### ISSUE THREAD

**Issue by pbrzosko** [intlify/vue-i18n-next#810]
### Reporting a bug?

Unfortunately, this issue still reproduces when using JS instead of TS.
I have attached an example repo to reproduce
[test.zip](https://github.com/intlify/vue-i18n-next/files/7598831/test.zip)
.

### Expected behavior

According to your comment in #789 this should not happen if plugin is used for vite.

### Reproduction

Please use a repo attached as test.zip. Simply run it with vite 'npm run dev'

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 471.07 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.1.2
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^3.2.1 => 3.2.1 
    @vitejs/plugin-vue: ^1.9.3 => 1.10.0 
    vite: ^2.6.4 => 2.6.14 
    vue: ^3.2.16 => 3.2.22 
    vue-i18n: ^9.1.9 => 9.1.9 
    vue-tsc: ^0.3.0 => 0.3.0
```

### Screenshot

![Zrzut ekranu 2021-11-24 o 22 38 02](https://user-images.githubusercontent.com/67122459/143316014-f3ff08a8-6656-4378-bbc8-0d65ee38ce82.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by pbrzosko** [comment]
Unfortunately it also happens with my simple project setup with TS.
Can you please then indicate what am I doing wrong?

**Comment by kazupon** [comment]
Thank you for your reporting!

I tried to reproduce this issue.
In dev mode (`vite dev`), This warning is intended.
In production build, we need to optimize vue application bundle size, so in dev mode, this warning is shown to the console.
In the production build, this warning message will not show this warning.

See the following docs for more:

- Dist files for bundler: https://vue-i18n.intlify.dev/installation.html#with-a-bundler
- feature flags: https://vue-i18n.intlify.dev/guide/advanced/optimization.html#reduce-bundle-size-with-feature-build-flags

Thanks!

**Comment by pbrzosko** [comment]
Hi,

ok, so as I understand this warning is for production build. Why do I see it then in dev mode? I would expect that if such warning is shown it requires me to perform some action because something is not right. I am constantly checking console during development too see if everything is allright.
Can you print this message only in prod build?

**Comment by Shamzic** [comment]
Hello, I fixed this warning by adding the plugin here : https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n

**Comment by zorn-v** [comment]
There is a bug in v9.1.9
https://github.com/intlify/vue-i18n-next/blob/v9.1.9/packages/vue-i18n/src/misc.ts#L39 will compiled to
```js
if ((process.env.NODE_ENV !== 'production') && typeof true === 'boolean') {
    needWarn = true;
}
```

**Comment by kazupon** [comment]
Fixed with #997

**Comment by vesper8** [comment]
I'm using `vue-i18n@9.1.10` which should include this fix, but I'm still seeing the warning on dev?

**Comment by zorn-v** [comment]
It means this warning for you )

**Comment by hmingv** [comment]
> 我正在使用`vue-i18n@9.1.10`which 应该包含此修复程序，但我仍然在 dev 上看到警告？

Me too

**Comment by wallereducbank** [comment]
> I'm using `vue-i18n@9.1.10` which should include this fix, but I'm still seeing the warning on dev?

Me too

**Comment by mikeogi** [comment]
helped me:
https://v3.nuxtjs.org/api/configuration/nuxt.config
```
// nuxt.config.ts
export default defineNuxtConfig({
    srcDir: './src',
    vite: {
        define: {
            __VUE_I18N_FULL_INSTALL__: true,
            __VUE_I18N_LEGACY_API__: true,
            __INTLIFY_PROD_DEVTOOLS__: false
        }
    },
})
```
