### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '__composer')

### ISSUE THREAD

**Issue by kolaente** [intlify/vue-i18n-next#896]
### Reporting a bug?

Follow up for https://github.com/intlify/vue-i18n-next/issues/793#issuecomment-1015856474

I'm hitting a slightly similar error to #793 with the latest version 9.2.0-beta.28:

![image](https://user-images.githubusercontent.com/13721712/150022546-bd6569ad-827a-4cf1-baec-26de53446cf9.png)

I could not notice if it has any effects on the UI of my application but the errors are really annoying.

The code section (copied from dev tools):

```js
        mounted() {
            nextTick(() => {
                /* istanbul ignore if */
                if (((process.env.NODE_ENV !== 'production') || __VUE_PROD_DEVTOOLS__) &&
                    !false &&
                    this.$el) {
                    this.$el.__VUE_I18N__ = this.$i18n.__composer;
                    const emitter = (this.__v_emitter =
                        createEmitter());
                    const _vueI18n = this.$i18n;
                    _vueI18n.__enableEmitter && _vueI18n.__enableEmitter(emitter);
                    emitter.on('*', addTimelineEvent);
                }
            });
        },
```

### Expected behavior

No error in console.

### Reproduction

This isn't a minimal reproduction of the bug, but I'm not sure how I should reproduce it - even in my application I can't understand why it happens and it does not happen all the time.

1. Check out https://kolaente.dev/vikunja/frontend at commit `55b77725df4a71ea248fbee2eb7b613fc590f6aa`
2. Install dependencies with `yarn install`
3. Start the dev server with `yarn serve`
4. Using chrome, open the app at `localhost:5000`
5. As an api url, use `https://try.vikunja.io`
6. Use `demo` as a username and password.
7. Click around in the app a bit with dev tools openend, the error will appear eventually.

### System Info

```shell
System:
    OS: Linux 5.10 NixOS 21.11 (Porcupine) 21.11 (Porcupine)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 12.41 GB / 31.37 GB
    Container: Yes
    Shell: 5.8 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 14.18.1 - /etc/profiles/per-user/konrad/bin/node
    Yarn: 1.22.17 - /etc/profiles/per-user/konrad/bin/yarn
    npm: 6.14.15 - /etc/profiles/per-user/konrad/bin/npm
  Browsers:
    Chromium: 97.0.4692.71
    Firefox: 95.0.2
  npmPackages:
    @vitejs/plugin-legacy: 1.6.4 => 1.6.4
    @vitejs/plugin-vue: 2.1.0 => 2.1.0
    @vue/compat: 3.2.28 => 3.2.28
    @vue/eslint-config-typescript: 10.0.0 => 10.0.0
    vite: 2.7.13 => 2.7.13
    vite-plugin-pwa: 0.11.13 => 0.11.13
    vite-svg-loader: 3.1.2 => 3.1.2
    vitest: 0.1.27 => 0.1.27
    vue: 3.2.28 => 3.2.28
    vue-advanced-cropper: 2.7.1 => 2.7.1
    vue-drag-resize: 2.0.3 => 2.0.3
    vue-flatpickr-component: 9.0.5 => 9.0.5
    vue-i18n: 9.2.0-beta.28 => 9.2.0-beta.28
    vue-router: 4.0.12 => 4.0.12
    vue-tsc: 0.30.6 => 0.30.6
    vuedraggable: 4.1.0 => 4.1.0
    vuex: 4.0.2 => 4.0.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!

I've just tried your reproduction site, but unfortunately, I could not reproduce this issue 😞 

The code section is provided with you, It would be helpd to the solution for me.

I'll give it some more thought later.
Thanks!

**Comment by kolaente** [comment]
It looks like this is happening here: https://github.com/intlify/vue-i18n-next/blob/ac341b6f0977839d8cf19a41607d7b2983e21d3e/packages/vue-i18n-core/src/mixins/next.ts#L110 and is caused by `this.$i18n` being undefined. Because the function happens in the `mounted()` hook of the mixin, I'm not sure what might have caused it. Does not look like it's getting called by something.

What could cause the `this.$i18n` property to get deleted? Maybe we should start to look from there?

**Comment by kazupon** [comment]
Yeah!
I understood about it.
I need to find out why it has been removed or left undefined.

**Comment by kolaente** [comment]
Anything I can do to help debug this?

**Comment by apetrenkov** [comment]
FYI: got this on 9.1.9

**Comment by kazupon** [comment]
@kolaente 
>Click around in the app a bit with dev tools openend, the error will appear eventually.
System Info

Thanks!
I would like to know the pattern that will reproduce reliably in your application.

I will find out the cause from your stack trace.
I guess that it has something to do with the `loadPendingTasks` call via the `create` hook in `ShowTask.vue`.

**Comment by christianbayer** [comment]
Hey! I'm having the same issue. Debugging a little bit, starting with what @apetrenkov saw, I found that commenting out  the `delete this.$i18n` "solves" the problem..

https://github.com/intlify/vue-i18n-next/blob/ac341b6f0977839d8cf19a41607d7b2983e21d3e/packages/vue-i18n-core/src/mixins/next.ts#L153

Apparently not all components throws this error, just the ones wrapped in a `v-if` or something, which are created and destroyed too quickly.

Wondering if there is a chance of the `unmounted` hook being called before the `mounted` one..

**Comment by kazupon** [comment]
@christianbayer 
Thank you for your reporting!
Your information is going to be very helpful in solving this issue ❤️ 

It looks like running nextTick is probably causing this issue due to Vue lifecycle order miss-match.

I appreciate your PR, but we still cannot find out the root cause. if we don't know the root cause, even if we fix it, it will cause the same issue again.

**Comment by elboukhari** [comment]
Sorry I've created this one https://github.com/intlify/vue-i18n-next/issues/906 before reading this thread. Will close it. 
Indeed my v-text-field is in dialog/modal component so maybe it will be helpfull as it seems to be related to vue lifecycle

**Comment by christianbayer** [comment]
@kazupon I just tried it with v9.2-beta.30 and now it's working with no errors.

**Comment by kolaente** [comment]
Can confirm it looks like it is fixed with v9.2-beta.30. Thanks everyone!

**Comment by kazupon** [comment]
Thanks, everyone!
Happy coding! :)

**Comment by elboukhari** [comment]
HI @kazupon, not for me :( 


```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 15.93 GB / 31.34 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.18362.1593.0)
    Internet Explorer: 11.0.18362.1766
  npmPackages:
    @vitejs/plugin-vue: ^1.9.0 => 1.10.2
    @vue/cli-plugin-babel: 5.0.0-beta.7 => 5.0.0-beta.7
    @vue/cli-service: 5.0.0-beta.7 => 5.0.0-beta.7
    @vue/eslint-config-prettier: 6.0.0 => 6.0.0
    @vue/eslint-config-typescript: 9.1.0 => 9.1.0
    @vuetify/nightly:  3.0.0-next-20220126.0
    vite: ^2.7.13 => 2.7.13
    vue: ^3.2.29 => 3.2.29
    vue-i18n: ^9.2.0-beta.30 => 9.2.0-beta.30
    vue-router: ^4.0.12 => 4.0.12
```



![image](https://user-images.githubusercontent.com/36670922/151502150-603abfa2-9334-4001-a6d9-fa6d1921abd8.png)

**Comment by kazupon** [comment]
Your error report is a different issue. Please open a new issue.

**Comment by elboukhari** [comment]
done here : https://github.com/intlify/vue-i18n-next/issues/909

**Comment by ManuLmz** [comment]
Hi! Same problem with 9.1.10 (also tried 9.1.9 and 9.1.8). Not happening with 9.2.0-beta.36.

![imagen](https://user-images.githubusercontent.com/6280807/172884784-521eb5b1-7e5d-41b0-8e15-8dc61b77563f.png)

Any chance for a fix in 9.1.x or a non-beta version?

Thanks!

**Comment by m3hari** [comment]
@kazupon  We still have this issue  on `9.1.10`
<img width="1914" alt="Screenshot 2023-03-23 at 10 35 04" src="https://user-images.githubusercontent.com/9920926/227076429-abd9c803-16b1-4922-abb4-4ea81b962c84.png">
